server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book_service
    username: ezequiel
    password: 123456
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  flyway:
    url: jdbc:postgresql://localhost:5432/book_service
    user: ezequiel
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
      foo-bar:
        max-attempts: 4
        wait-duration: 1s
        enable-exponential-backoff: true
  bulkhead:
    instances:
      tests:
        max-concurrent-calls: 1
        max-wait-duration: 10ms
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  swagger-ui:
    path: book-service/swagger-ui.html
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoin